---
title: "Final paper Maps code KH"
author: "Katherine"
date: '2022-04-24'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel", 
#"ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata"))

library("ggplot2")
theme_set(theme_bw())
library("sf")

library("rnaturalearth")
library("rnaturalearthdata")
library("maps")
library("ggplot2")
library("tools")
library("dplyr")

world <- ne_countries(scale = "medium", returnclass = "sf")
class(world)

```

#Reading in data
```{r}
data1 <- read.csv("Cunning_ED50.csv")

summary(data1)
```

Putting in coordinates for RR and CRF nurseries
```{r}
(sites <- data.frame(longitude = c(-80.43, -80.43), latitude = c(24.985, 
    24.980)))

# "CRF", 24.98, -80.43,
# "RR", 24.98, -80.43,
```
#adding my points to generated map

```{r}
relevantGenos <- data1 %>% 
  filter(nursery %in% c("CRF", "RR"))

ggplot(data = world) +
    geom_sf() +
    geom_point(data = relevantGenos, aes(x=source_lon, y = source_lat, color = nursery), shape = 21) +
    geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = 5, color = "dark green") +
    scale_color_brewer(palette = "Dark2") +
    coord_sf(xlim = c(-83, -79), ylim = c(24, 26.5), expand = TRUE) +
    labs(title = "Map of Nurseries & Source Locations for Acropora CBASS",
         x = "Longitude", y= "Latitude",
         color = "Collecting Nursery") +
    
    theme(legend.position="bottom")
```

```{r}
ggplot(data = world) +
    geom_sf() +
    geom_point(data = data1, aes(x=source_lon, y = source_lat, color = nursery), shape = 21) +
    geom_point(data = sites, aes(x = longitude, y = latitude), size = 4, 
        shape = 5, color = "dark green") +
    scale_color_brewer(palette = "Dark2") +
    coord_sf(xlim = c(-83, -79), ylim = c(24, 26.5), expand = TRUE) +
    labs(title = "Map of Nurseries & Source Locations for A.cervicornis CBASS",
         x = "Longitude", y= "Latitude",
         color = "Collecting Nursery") +
    theme(legend.position="bottom")
```


